### PR TITLE
moved the totalListCost outside of the list array

### PR DESCRIPTION
**Pull request by psyduc**
Edit(josh): Fix for #116

### CODE REVIEW

**Comment by jwu910** [comment]
ci:retest

**Review by jwu910 — CHANGES_REQUESTED** [review]
@psyduc Please resolve conflicts and adjust commit message to follow agreed commit message standards. 

Did you pull latest before you branched?

**Comment by jwu910** [comment]
Fix for #116

**Comment by rainrivas** [comment]
It looks like this branch is very dated and that's why travis is very upset

**Review by rainrivas — CHANGES_REQUESTED** [review]
pull models into AAF-116-totalListCost

**Comment by psyduc** [comment]
hmm my models branch is tracking my delete route. is this suppose to happen?

**Comment by jwu910** [comment]
@psyduc 

image

**Comment by jwu910** [comment]
~~@psyduc  are you working on a fork?~~

Nvm, you are not.

**Comment by rainrivas** [comment]
@psyduc it is not supposed to happen. also, ~~it looks to me that your models branch is tracking models...`AAF-63-models .......origin/AAF-63-models`~~
You also have 2 branches that you are tracking locally that don't have a remote counterpart -- you should clean those up as well.
** EDIT ** this is actually meant for @jwu910 since those are his branches not yours...

**Comment by jwu910** [comment]
@rainrivas lol yeah. Haven't cleaned up in a bit.

**Comment by jwu910** [comment]
@psyduc Did you need any help with this?

**Comment by rainrivas** [comment]
@jwu910 we haven't touched it but we'll handle it sometime this week/sprint. Is it blocking anyone?

**Comment by jwu910** [comment]
Yeah its blocking my issue, but I'm not ready for pr, so no rush

**Review by rainrivas — APPROVED** [review]

**Comment by rainrivas** [comment]
@jwu910 if you're not ready to push and you're still working then it's not blocking you right now. Unless you mean that this your dependency to finish the work

**Comment by jwu910** [comment]
@rainrivas Oh. that makes sense... Well i need it to continue working w/o making a temporary change...

**Review by jwu910 — APPROVED** [review]

**Comment by rainrivas** [comment]
@jwu910 we finished it

**Comment by jwu910** [comment]
@rainrivas lol i figured that much. Just responding to the blocker comment

**Pull request merged**
