### PR TITLE
removed constructor from class components and add tbody to table

### PR DESCRIPTION
**Pull request by riceball1**
@phuchle I made some contributions, but not sure how to do the pull request here, since I had forked the repo, and created a feature branch, should I be doing a pull request into development in your adopt-a-family repo?

### CODE REVIEW

**Comment by jwu910** [comment]
Hi @riceball1 Did you happen pull in the latest changes from development? We made a bunch of big changes that were merged in to development. I don't think you have them on your branch. I noticed you still have material-ui, on your fork, but we had removed it on one of our recent PRs. 

Also, I'm working on refactoring the Input, Select, and Form components and some of your changes may be irrelevant on those components. 

Would you be able to get the latest changes on development and resolve any local conflicts you may have and update the PR?

Thanks for the time and the work! I'm sending daily(usually) PRs to our topic branch [AAF-73](https://github.com/5-gwoap/adopt-a-family/pull/81) if you want to take a look at what I'm trying to do.

**Comment by riceball1** [comment]
@jwu910 yep no problem, I'll do that now

**Comment by riceball1** [comment]
@jwu910 -- so updated the new changes from development, in a way issue #65 is no longer relevant? Then we should close this pull request right?

**Comment by jwu910** [comment]
@riceball1 

Sorry I was away from my keyboard for a few hours. I think we would need to check with @phuchle regarding his issue #65 . While reading over his issue description, it sounds to me that he wants to remove unnecessary constructor methods. 

Looking through our current development branch, we're really only using it on [Form.js](https://github.com/5-gwoap/adopt-a-family/blob/development/src/components/Form.js). My current WIP changes on Input.js are using it--but there may be a better way to write it. 

I'm going to leave the issue open until Phuc gets a chance to review.

Thanks again for your help!

**Pull request closed without merging**
