### PR TITLE
AAF-141

### PR DESCRIPTION
**Pull request by jwu910**
Add typescript compiler, convert main and app to tsx files, Initial typescript ecosystem setup and will need additional tickets/PRs to continue to refactor rest of application and possibly clean up some unused dependencies.

### CODE REVIEW

**Comment by jwu910** [comment]
Bump

**Review by rainrivas — APPROVED** [review]
Looks good to me mang. 
**EDIT:: We will need to fix travis before we merge. Seems to be a bcrypt node module error with node latest, and then we have lint and jest failures on node LTS (8) and 7**

**Comment by jwu910** [comment]
I'll get the travis config updated soon. Some of the tests were changed and should have been consolidated

**Review by phuchle — COMMENTED** [review]
Did you try to add typescript without ejecting? https://create-react-app.dev/docs/adding-typescript/ Looks like updating to react-scripts 2.x may work.

**Comment by jwu910** [comment]
@phuchle Hmm. I haven't really used CRA much. I just removed react-scripts deps and updated the scripts to the manual webpack configs and installed the dependencies. From what I remember, I thought thats what react scripts eject does anyways.

**Comment by phuchle** [comment]
I'd like to do this without ejecting so we don't have to manage dependencies ourselves. I can give it a go on another branch if you would like.

**Comment by jwu910** [comment]
You can give it a shot, personally I prefer the manual dep management. Maybe illusion of control haha. But I think its good visibility and it gives me a chance to understand exactly what we're using.

**Comment by phuchle** [comment]
@rainrivas your thoughts on eject/no eject?

**Comment by rainrivas** [comment]
@jwu910 @phuchle  I recall us initially discussing wanting to eject pre-react 2.x, however I would prefer not to manage dependencies as it's a pretty large overhead. If we stick with letting react manage dependencies we won't have to worry about "does updating X break react"
**EDIT: "... wanting to eject pre _reactScripts_ 2.x**

**Pull request closed without merging**
