### PR TITLE
Adding a lot of the rules from eslint:recommend. Adding these rules t…

### PR DESCRIPTION
**Pull request by rainrivas**
…o keep code cleaner and easier to read; also set it up to catch typos and accidental re-assigns/conditionals

### CODE REVIEW

**Comment by rainrivas** [comment]
2 thoughts / points here 
1. Tests are failing due to linting not passing. That is because of the `__test__` folder having code which breaks the new rules.
  a. You guys decide what do on that one, I can create a new commit to add it to ignore files or we can leave it as it and fix it later
2. When we do decide to merge this, lets just rebase it or squash it

**Review by jwu910 — COMMENTED** [review]
@rainrivas when you review, you may want to close this PR and reopen against dev branch.

**Review by jwu910 — APPROVED** [review]
:clap:

**Review by phuchle — APPROVED** [review]
Thanks for walking us through this on discord lol.

**Pull request merged**
