### PR TITLE
Closing #30 by connecting to Heroku

### PR DESCRIPTION
**Pull request by rainrivas**

### CODE REVIEW

**Comment by phuchle** [comment]
A couple questions:

1. Is there a way to have automate the deployment process to heroku?  I've set up a script in package.json to run all the build commands in the past, so maybe we could do that again, or maybe heroku supports that somewhere.

2. Can we get an update to the README going for deploying to Heroku?

**Comment by rainrivas** [comment]
@phuchle 
---

>1. Is there a way to have automate the deployment process to heroku? I've set up a script in package.json to run all the build commands in the past, so maybe we could do that again, or maybe heroku supports that somewhere.

Heroku Dashboard supports auto-deployments for specific branches and we can set up pipelines there. I know the auto-deployments can build the pages we want but won't do "react-scripts build" since it only installs dependencies and not DevDepends. I think to achieve this you would want to use the Pipeline feature which I haven't deep-dived yet.

---

>2. Can we get an update to the README going for deploying to Heroku?

I can write one if we need it, but it would probably be mostly around Heroku since the only thing we have to do in AAF is locally run `npm build` then push up the resulting build folder.

**Comment by phuchle** [comment]
@rainrivas 

> Heroku Dashboard supports auto-deployments for specific branches and we can set up pipelines there. I know the auto-deployments can build the pages we want but won't do "react-scripts build" since it only installs dependencies and not DevDepends. I think to achieve this you would want to use the Pipeline feature which I haven't deep-dived yet.

OK, I think that can be saved until later on in the dev. pipeline.

> I can write one if we need it, but it would probably be mostly around Heroku since the only thing we have to do in AAF is locally run npm build then push up the resulting build folder.

Yeah that would be great.  Can we review the steps on discord whenever you're free so I can learn how the deployment goes down?

**Review by phuchle — APPROVED** [review]

**Comment by rainrivas** [comment]
@phuchle Yeah I think for now we can keep the build files but we definitely want to revisit later. However, in the end when we host this, we would be pushing build files and storing them on the server. I really do think that setting up the pipeline process has to be done eventually.

I can show everyone how to use the Heroku environment. If any of the team members don't have access to Heroku I can add them later too.

**Review by psyduc — APPROVED** [review]

**Review by AlChiu — APPROVED** [review]

**Review by jwu910 — APPROVED** [review]
To the extent of my backend knowledge, this looks good

**Comment by jwu910** [comment]
@rainrivas @phuchle 

If heroku reads from the designated branch build folder, could we just make sure our build script sets up everything we need, if not, would we need to consider looking into a simple task runner like gulp?

**Comment by rainrivas** [comment]
@jwu910 I think webpack handles the compiling and transpiling. All heroku does (right now) is read the build folder that react-scripts creates. Eventually we should sophisticate our pipeline to include more than 1 step. We can discuss this over discord in more detail on tuesday

**Pull request merged**
