### PR TITLE
Revert 45 frontend content

### PR DESCRIPTION
**Pull request by jwu910**
Revert last PR.

### CODE REVIEW

**Comment by rainrivas** [comment]
Delete this,  we don't want 86 revert commits.  Ill clean master later

**Comment by jwu910** [comment]
One revert commit okay? I can check out, rebase and squash

**Comment by rainrivas** [comment]
@jwu910 One big-ole undo is cool with me I think. I am in an all day meeting so i can't work on it for awhile

**Review by rainrivas — DISMISSED** [review]
Mistakes were made...

**Comment by rainrivas** [comment]
@jwu910 we need to cherry pick the "setting up travis" and put that into this branch so that it can build

**Comment by jwu910** [comment]
I think I can do that during lunch.

**Comment by rainrivas** [comment]
Refer to PR #10 
SHA to cherry pick from b37d03996576ca90ca1d30ecddb587cc56e1f25a
we'll probably grab the linter and package.json changes too

**Comment by phuchle** [comment]
@jwu910 what will happen to the history if this PR goes through?

**Comment by jwu910** [comment]
In all transparency, I dont have the slightest clue, but we're not going to have 160 commits of garbage. 
I think we could also rewrite master history >.> or accept our mistakes and let our commit history be a reminder to check our base branches.

**Comment by rainrivas** [comment]
@phuchle @jwu910 
> what will happen to the history if this PR goes through?

we will see the mass number of commits from the last PR, then we will see 1 really big squashed commit that reads "Revert accidental PR to master"

**Comment by phuchle** [comment]
@rainrivas I can live with that.

**Review by phuchle — DISMISSED** [review]

**Review by rainrivas — APPROVED** [review]
FYI -- I'm okay with this, but despite having pulled in #10 we didn't get the eslintrc file, therefore the test command will always pass (it's testing nothing). This is fine for master I guess but yeah, just giving you an FYI.

**Comment by jwu910** [comment]
@rainrivas Loll, I did notice that. but it didn't have conflicts and tests started. Figured the other commits would pull it in later anyways.

**Comment by rainrivas** [comment]
@jwu910 yup. I'm good with it. If @phuchle has no problem we can merge this thing.

**Review by phuchle — APPROVED** [review]

**Pull request merged**
