### PR TITLE
Updated editor config to use space characters. maintain 2 space chara…

### PR DESCRIPTION
**Pull request by jwu910**
…cters per indent

### CODE REVIEW

**Review by rainrivas — APPROVED** [review]

**Comment by phuchle** [comment]
Sanity check: this fixes [issue 8](https://github.com/5-gwoap/adopt-a-family/issues/8)?

**Comment by rainrivas** [comment]
@phuchle 
> Sanity check: this fixes issue 8?

Yes it does

**Comment by jwu910** [comment]
We clear to merge?

**Review by phuchle — APPROVED** [review]

**Comment by phuchle** [comment]
@jwu910 merged.

**Pull request merged**
