### PR TITLE
Aaf 110 donors filter

### PR DESCRIPTION
**Pull request by phuchle**
This PR adds the routes `api/donors` and `/api/donors/:filter`.

To show all donors, make a GET request to `api/donors` with no query fields.
To filter by one field:
GET: `/donors/_id?value=123 // Returns array of donors matching or empty array if no matches`

### CODE REVIEW

**Review by jwu910 — CHANGES_REQUESTED** [review]
Theres a merge conflict that should be resolved. Probably rebase on to AAF-63-models first. Or just fix conflict in GUI .

I'm good with all this. I think I'm gonna need some time to really crawl through everything we've done again.

**Review by rainrivas — CHANGES_REQUESTED** [review]
Travis looks to be failing due to some issue downloading it's own dependencies so I don't see how it would be a problem for the test executions, however, the conflict needs to be resolved first. Aside from that warning, everything does look good to me.

**Review by rainrivas — APPROVED** [review]

**Comment by jwu910** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jwu910** [comment]
Latest build is still failing due to i think a bcrypt min version requirement for latest node. 

https://github.com/kelektiv/node.bcrypt.js#version-compatibility

Should we upgrade to >=3.0?

**Comment by rainrivas** [comment]
@jwu910 I am not so sure that is the fix, but I'm down to try. `bcrypt` [page on npm](https://www.npmjs.com/package/bcrypt) says a few different things...

----

Node Version | Bcrypt Version
-- | --
0.4.x | <= 0.4.x
0.6.x | >= 0.5.x
0.8.x | >= 0.5.x
0.10.x | >= 0.5.x
0.11.x | >= 0.8.x
4.x.x | <= 2.0.x
8.x.x | >= 1.0.3
10.x.x | >= 3.0.0

node-gyp only works with stable/released versions of node. Since the bcrypt module uses node-gyp to build and install you'll need a stable version of node to use bcrypt. If you do not you'll likely see an error that starts with:
```
gyp ERR! stack Error: "pre" versions of node cannot be installed, use the --nodedir flag instead
```

**EDIT**:: We could create a TODO to update bcrypt to v3.0 anyway since it says that would support everything. Currently we are at `^1.x.y` so we would never make it to even 2.0; we need to make sure our code is compatible with 3.x

**Comment by phuchle** [comment]
@rainrivas We probably need a PR that updates a lot of the packages, since GH is warning about vulnerabilities  .

**Comment by jwu910** [comment]
@phuchle Yeah, figured we could do that, I commented on the dependency for this PR just cause Travis was erring one of its builds. Not sure what the best course of action was

**Review by jwu910 — APPROVED** [review]
Gucci. Lgtm

**Pull request merged**
